import { ScenarioItem, ShadowingItem } from "../types";

// 120 phrases d'entraînement en allemand pour un jeune handballeur (gardien) :
// entraînement avec le coach, communication avec les coéquipiers en match,
// échanges fair-play avec les adversaires et discussions avec l'arbitre.
// Chaque phrase a sa traduction française et un conseil de prononciation
// en français ciblant les difficultés typiques : les sons ich/ach, ü/ö,
// le R allemand, Z = /ts/, W = V, sch/st/sp, äu/eu = « oy », ei = « aï ».
export const HANDBALL_SHADOWING: ShadowingItem[] = [
  // ── Entraînement : parler avec le coach ────────────────────────────────────
  {
    id: "hb-1",
    text: "Trainer, können wir den Sprungwurf noch einmal üben?",
    translation: "Coach, on peut encore travailler le tir en suspension ?",
    tip: "Arrondis les lèvres pour le « ü » de « üben » — comme le « u » français.",
  },
  {
    id: "hb-2",
    text: "Ich habe verstanden, dass ich schneller zurücklaufen muss.",
    translation: "J'ai compris que je dois revenir défendre plus vite.",
    tip: "« Ich » : un son doux /ç/, comme un souffle — ni « ich-k » ni « ich-ch ».",
  },
  {
    id: "hb-3",
    text: "Soll ich heute im Angriff oder in der Abwehr spielen?",
    translation: "Je joue en attaque ou en défense aujourd'hui ?",
    tip: "Accentue « Angriff » sur la première syllabe ; « Abwehr » a un « e » long.",
  },
  {
    id: "hb-4",
    text: "Mein Wurf war heute besser als letzte Woche.",
    translation: "Mon tir était meilleur aujourd'hui que la semaine dernière.",
    tip: "Le W allemand = V français : « Wurf » = /vourf/, « Woche » = /vorreu/.",
  },
  {
    id: "hb-5",
    text: "Entschuldigung, ich komme fünf Minuten später zum Training.",
    translation: "Excusez-moi, j'arrive cinq minutes en retard à l'entraînement.",
    tip: "« fünf » : « u » français court ; « später » : « ä » long comme « è ».",
  },
  {
    id: "hb-6",
    text: "Können Sie mir zeigen, wie ich den Kreisläufer decke?",
    translation: "Vous pouvez me montrer comment défendre sur le pivot ?",
    tip: "« Kreisläufer » : accent sur « Kreis » ; « äu » = « oy » comme dans « boy ».",
  },
  {
    id: "hb-7",
    text: "Ich möchte am Wochenende beim Turnier mitspielen.",
    translation: "Je voudrais jouer au tournoi ce week-end.",
    tip: "« möchte » : « ö » = « eu » français, puis le son doux /ç/.",
  },
  {
    id: "hb-8",
    text: "Der Torwart hat heute wirklich stark gehalten.",
    translation: "Le gardien a vraiment fait de super arrêts aujourd'hui.",
    tip: "R allemand au fond de la gorge dans « Torwart » et « wirklich ».",
  },
  {
    id: "hb-9",
    text: "Ich glaube, unsere Abwehr muss enger zusammenstehen.",
    translation: "Je pense que notre défense doit être plus resserrée.",
    tip: "Le « z » de « zusammen » = /ts/ comme dans « tsé-tsé », jamais un Z français.",
  },
  {
    id: "hb-10",
    text: "Nach dem Training tut mir die Schulter ein bisschen weh.",
    translation: "Après l'entraînement, j'ai un peu mal à l'épaule.",
    tip: "« Schulter » commence par « ch » français ; « bisschen » a le son doux /ç/.",
  },
  {
    id: "hb-11",
    text: "Wie viele Tore haben wir im letzten Spiel geworfen?",
    translation: "Combien de buts avons-nous marqués au dernier match ?",
    tip: "« Wie viele » : les deux commencent par /v/ ; « o » long dans « Tore ».",
  },
  {
    id: "hb-12",
    text: "Ich passe den Ball schneller ab, wenn der Gegner drückt.",
    translation: "Je passe le ballon plus vite quand l'adversaire presse.",
    tip: "« drückt » : « u » français court, lèvres arrondies ; « t » final net.",
  },
  {
    id: "hb-13",
    text: "Dürfen wir am Ende noch Siebenmeter werfen üben?",
    translation: "On peut travailler les jets de sept mètres à la fin ?",
    tip: "« Dürfen » et « üben » : « u » français ; « Siebenmeter » : « ie » long /i/.",
  },
  {
    id: "hb-14",
    text: "Ich übernehme die Manndeckung gegen ihren besten Spieler.",
    translation: "Je prends le marquage individuel sur leur meilleur joueur.",
    tip: "Accentue « übernehme » sur « neh » ; premier « e » long dans « gegen ».",
  },
  {
    id: "hb-15",
    text: "Das Zusammenspiel mit dem Kreisläufer hat gut funktioniert.",
    translation: "La combinaison avec le pivot a bien fonctionné.",
    tip: "/ts/ dans « Zusammenspiel » ; accentue « funktioniert » sur « niert ».",
  },
  {
    id: "hb-16",
    text: "Trainer, welche Übung machen wir zum Aufwärmen?",
    translation: "Coach, quel exercice fait-on pour l'échauffement ?",
    tip: "« Übung » : « u » français long au début ; « Aufwärmen » : « ä » comme « è ».",
  },
  {
    id: "hb-17",
    text: "Ich versuche, beim Tempogegenstoß schneller anzulaufen.",
    translation: "J'essaie de démarrer plus vite sur la contre-attaque.",
    tip: "Découpe : Tempo-gegen-stoß. « ß » = un « s » net ; « o » long avant.",
  },
  {
    id: "hb-18",
    text: "Unsere Mannschaft kämpft bis zur letzten Minute.",
    translation: "Notre équipe se bat jusqu'à la dernière minute.",
    tip: "« kämpft » : « ä » court puis le groupe /mpft/ — vas-y lentement d'abord.",
  },
  {
    id: "hb-19",
    text: "Beim nächsten Angriff spiele ich den Ball auf Rechtsaußen.",
    translation: "Sur la prochaine attaque, je passe le ballon à l'ailier droit.",
    tip: "« nächsten » : son doux /ç/ ; « Rechtsaußen » finit sur un « en » clair.",
  },
  {
    id: "hb-20",
    text: "Danke für das Training, ich habe heute viel gelernt.",
    translation: "Merci pour l'entraînement, j'ai beaucoup appris aujourd'hui.",
    tip: "« für » : « u » français ; R allemand dans « gelernt » ; « viel » = /fil/ long.",
  },
  {
    id: "hb-21",
    text: "Trainer, ich fühle mich fit genug für die erste Mannschaft.",
    translation: "Coach, je me sens assez en forme pour l'équipe première.",
    tip: "« fühle » : « u » français long ; « genug » finit par un son /k/.",
  },
  {
    id: "hb-22",
    text: "Kann ich beim nächsten Spiel von Anfang an spielen?",
    translation: "Je peux être titulaire au prochain match ?",
    tip: "« nächsten » avec le /ç/ doux ; accentue « Anfang » sur la première syllabe.",
  },
  {
    id: "hb-23",
    text: "Welche Fehler habe ich im letzten Spiel gemacht?",
    translation: "Quelles erreurs ai-je faites au dernier match ?",
    tip: "« Fehler » : « e » long, finale relâchée /ɐ/ presque « a ».",
  },
  {
    id: "hb-24",
    text: "Ich arbeite zu Hause zusätzlich an meiner Sprungkraft.",
    translation: "Je travaille aussi ma détente à la maison.",
    tip: "/ts/ deux fois : « zu » et « zusätzlich » ; « Sprungkraft » commence par « chp ».",
  },
  {
    id: "hb-25",
    text: "Mir fällt das Fangen mit der linken Hand noch schwer.",
    translation: "Attraper de la main gauche est encore difficile pour moi.",
    tip: "« fällt » : « ä » court comme « è » ; « schwer » : « ch » + V — /chvér/.",
  },
  {
    id: "hb-26",
    text: "Sollen wir heute mehr an der Wurftechnik arbeiten?",
    translation: "On devrait travailler plus la technique de tir aujourd'hui ?",
    tip: "« Wurftechnik » : W = V ; « Technik » avec /ç/ doux ; R allemand dans « arbeiten ».",
  },
  {
    id: "hb-27",
    text: "Ich trinke genug Wasser vor und nach dem Training.",
    translation: "Je bois assez d'eau avant et après l'entraînement.",
    tip: "« Wasser » = /vassa/ — W = V, double S net ; « vor » avec « o » long.",
  },
  {
    id: "hb-28",
    text: "Das Auslaufen am Ende hilft gegen Muskelkater.",
    translation: "Le retour au calme à la fin aide contre les courbatures.",
    tip: "« Auslaufen » : « au » comme « ao » dans « miaou » ; « Muskelkater » finit /ɐ/.",
  },
  {
    id: "hb-29",
    text: "Ich habe die Taktik für das Wochenende verstanden.",
    translation: "J'ai compris la tactique pour le week-end.",
    tip: "« Taktik » : les deux T bien nets ; accent sur la première syllabe.",
  },
  {
    id: "hb-30",
    text: "Können wir das Kreuzen zwischen Rückraum Mitte und Links üben?",
    translation: "On peut travailler le croisé entre l'arrière centre et l'arrière gauche ?",
    tip: "« Kreuzen » : « eu » = « oy » ; « zwischen » commence par /tsv/.",
  },
  // ── En match : parler aux coéquipiers ──────────────────────────────────────
  {
    id: "hb-31",
    text: "Hier, ich bin frei, spiel den Ball rüber!",
    translation: "Ici, je suis démarqué, passe-moi le ballon !",
    tip: "« Hier » = /hia/ ; « rüber » : « u » français + R allemand au début.",
  },
  {
    id: "hb-32",
    text: "Achtung, der Kreisläufer steht hinter dir!",
    translation: "Attention, le pivot est derrière toi !",
    tip: "« Achtung » : le /x/ dur comme la jota espagnole ; finale /ng/ sans « g » détaché.",
  },
  {
    id: "hb-33",
    text: "Gut gemacht, genau so machen wir weiter!",
    translation: "Bien joué, on continue exactement comme ça !",
    tip: "« gemacht » : /x/ dur avant le « t » final ; « weiter » finit /ɐ/.",
  },
  {
    id: "hb-34",
    text: "Wechsel! Ich gehe raus, du kommst rein.",
    translation: "Changement ! Je sors, tu entres.",
    tip: "« Wechsel » = /vèksel/ — « chs » se prononce « x » ; W = V.",
  },
  {
    id: "hb-35",
    text: "Langsam machen, wir haben Zeit für einen guten Abschluss.",
    translation: "On ralentit, on a le temps pour un bon tir.",
    tip: "« Zeit » : /ts/ au début, « ei » = « aï » ; « Abschluss » : double S net.",
  },
  {
    id: "hb-36",
    text: "Pass auf die Nummer sieben auf, sie wirft sehr stark.",
    translation: "Fais attention au numéro sept, il tire très fort.",
    tip: "« sieben » : « ie » long /i/ ; « wirft » avec le R allemand.",
  },
  {
    id: "hb-37",
    text: "Rückzug, alle schnell zurück in die Abwehr!",
    translation: "Repli, tout le monde revient vite en défense !",
    tip: "« Rückzug » : deux « u » français, /ts/ au milieu ; « g » final = /k/.",
  },
  {
    id: "hb-38",
    text: "Ich decke die Mitte, du nimmst den Halblinken.",
    translation: "Je couvre le centre, tu prends l'arrière gauche.",
    tip: "« Mitte » : « i » court, double T net ; L léger dans « Halblinken ».",
  },
  {
    id: "hb-39",
    text: "Kopf hoch, den nächsten Wurf machst du rein!",
    translation: "Garde la tête haute, le prochain tir tu le mets !",
    tip: "« hoch » : « o » long puis /x/ dur ; « nächsten » avec /ç/ doux.",
  },
  {
    id: "hb-40",
    text: "Super Parade! So halten wir das Spiel offen.",
    translation: "Super arrêt ! Comme ça le match reste ouvert.",
    tip: "« Parade » : accent sur « ra » ; « Spiel » commence par « chp » : /chpil/.",
  },
  {
    id: "hb-41",
    text: "Spiel schneller ab, sonst läuft die Zeit ab!",
    translation: "Passe plus vite, sinon le temps s'écoule !",
    tip: "« läuft » : « äu » = « oy » ; « Zeit » avec /ts/ et « aï ».",
  },
  {
    id: "hb-42",
    text: "Ich laufe den Gegenstoß, gib mir den langen Pass!",
    translation: "Je pars en contre-attaque, fais-moi la longue passe !",
    tip: "« Gegenstoß » : « o » long avant le « ß » net ; « gib » finit comme /p/.",
  },
  {
    id: "hb-43",
    text: "Bleib ruhig, wir holen das Tor wieder auf.",
    translation: "Reste calme, on va remonter ce but.",
    tip: "« ruhig » : « u » long, finit par le /ç/ doux ; « wieder » : « ie » long.",
  },
  {
    id: "hb-44",
    text: "Stellt den Block, ich übernehme den Schützen!",
    translation: "Faites le bloc, je prends le tireur !",
    tip: "« Stellt » commence par « cht » ; « Schützen » : « ch » + « u » français + /ts/.",
  },
  {
    id: "hb-45",
    text: "Guter Assist, dein Anspiel an den Kreis war perfekt.",
    translation: "Belle passe décisive, ton service au pivot était parfait.",
    tip: "« Anspiel » : « chp » au milieu ; « Kreis » : « ei » = « aï ».",
  },
  {
    id: "hb-46",
    text: "Wir spielen jetzt sieben gegen sechs, Torwart raus!",
    translation: "On joue maintenant à sept contre six, le gardien sort !",
    tip: "« sechs » = /zèks/ — « chs » = « x » ; « jetzt » : groupe /tst/, vas-y lentement.",
  },
  {
    id: "hb-47",
    text: "Noch zwei Minuten, volle Konzentration bis zum Schluss!",
    translation: "Encore deux minutes, concentration maximale jusqu'au bout !",
    tip: "« zwei » : /tsv/ au début, « ei » = « aï » ; « Schluss » : double S net.",
  },
  {
    id: "hb-48",
    text: "Ich habe den Siebenmeter verworfen, der nächste sitzt.",
    translation: "J'ai raté le sept mètres, le prochain fera mouche.",
    tip: "« verworfen » : deux R allemands, W = V ; « sitzt » : /ts/ avant le « t » final.",
  },
  {
    id: "hb-49",
    text: "Deine Abwehrarbeit heute macht den Unterschied.",
    translation: "Ton travail défensif aujourd'hui fait la différence.",
    tip: "« Unterschied » : « ch » au milieu, « ie » long, « d » final = /t/.",
  },
  {
    id: "hb-50",
    text: "Lass uns die erste Welle schneller laufen als bisher.",
    translation: "Courons la première vague plus vite qu'avant.",
    tip: "« Welle » : W = V, double L léger ; « bisher » : accent sur « her », « e » long.",
  },
  {
    id: "hb-51",
    text: "Ich bin angeschlagen, kannst du für mich weiterspielen?",
    translation: "Je suis touché, tu peux continuer à ma place ?",
    tip: "« angeschlagen » : « chl » au milieu ; deux fois /ng/ sans « g » détaché.",
  },
  {
    id: "hb-52",
    text: "Nach vorne schauen, das Spiel ist noch nicht vorbei!",
    translation: "On regarde devant, le match n'est pas encore fini !",
    tip: "« schauen » : « ch » + « ao » ; « nicht » avec /ç/ doux ; « vorbei » finit « aï ».",
  },
  {
    id: "hb-53",
    text: "Dein Sperren am Kreis öffnet mir den Wurfweg.",
    translation: "Ton écran au pivot m'ouvre l'angle de tir.",
    tip: "« öffnet » : « eu » court ; « Wurfweg » : deux W = V, « g » final = /k/.",
  },
  {
    id: "hb-54",
    text: "Wir ziehen das Tempo an, die sind schon müde.",
    translation: "On accélère le rythme, ils sont déjà fatigués.",
    tip: "« ziehen » : /ts/ puis « ie » long ; « müde » : « u » français long.",
  },
  {
    id: "hb-55",
    text: "Übernimm du den Siebenmeter, du bist heute sicherer.",
    translation: "Prends le sept mètres, tu es plus sûr aujourd'hui.",
    tip: "« Übernimm » : « u » français long au début ; « sicherer » : /ç/ doux, finit /ɐ/.",
  },
  // ── Parler aux adversaires (fair-play) ─────────────────────────────────────
  {
    id: "hb-56",
    text: "Gutes Spiel, eure Abwehr war heute richtig stark.",
    translation: "Bon match, votre défense était vraiment solide aujourd'hui.",
    tip: "« eure » : « eu » = « oy » ; « richtig » : deux /ç/ doux.",
  },
  {
    id: "hb-57",
    text: "Alles gut bei dir? Das war kein Foul mit Absicht.",
    translation: "Ça va ? Ce n'était pas une faute volontaire.",
    tip: "« Absicht » : /ç/ doux avant le « t » final ; « Foul » comme en anglais.",
  },
  {
    id: "hb-58",
    text: "Entschuldigung, ich wollte dich nicht am Arm treffen.",
    translation: "Excuse-moi, je ne voulais pas te toucher au bras.",
    tip: "« wollte » : W = V, double L léger ; « dich » et « nicht » avec /ç/ doux.",
  },
  {
    id: "hb-59",
    text: "Glückwunsch zum Sieg, ihr wart die bessere Mannschaft.",
    translation: "Félicitations pour la victoire, vous étiez la meilleure équipe.",
    tip: "« Glückwunsch » : « u » français court, finit « ch » ; « Sieg » : « ie » long, « g » = /k/.",
  },
  {
    id: "hb-60",
    text: "Starker Wurf, den konnte unser Torwart nicht halten.",
    translation: "Beau tir, notre gardien ne pouvait pas l'arrêter.",
    tip: "« Starker » commence par « cht » ; R allemand ; finit /ɐ/ relâché.",
  },
  {
    id: "hb-61",
    text: "Kannst du mir den Ball bitte kurz zurückgeben?",
    translation: "Tu peux me rendre le ballon s'il te plaît ?",
    tip: "« zurückgeben » : /ts/ au début, deux « u » français ; « bitte » : double T net.",
  },
  {
    id: "hb-62",
    text: "Wir sehen uns im Rückspiel, dann sind wir besser vorbereitet.",
    translation: "On se revoit au match retour, on sera mieux préparés.",
    tip: "« Rückspiel » : « u » français, « chp » ; « vorbereitet » : deux R allemands.",
  },
  {
    id: "hb-63",
    text: "Respekt, euer Torwart hat unglaublich gehalten heute.",
    translation: "Respect, votre gardien a fait des arrêts incroyables aujourd'hui.",
    tip: "« Respekt » : R allemand, « t » final net ; « unglaublich » finit /ç/ doux.",
  },
  {
    id: "hb-64",
    text: "Euer Kreisläufer ist kaum zu verteidigen, stark gespielt.",
    translation: "Votre pivot est presque indéfendable, bien joué.",
    tip: "« äu » de « Kreisläufer » = « oy » ; « verteidigen » : « ei » = « aï », finit « -gen ».",
  },
  {
    id: "hb-65",
    text: "Faires Spiel von euch, so macht Handball Spaß.",
    translation: "Match fair-play de votre part, c'est comme ça que le handball est un plaisir.",
    tip: "« Faires » comme « fair » + es ; « Spaß » : « chp », « a » long, « ß » net.",
  },
  // ── Parler à l'arbitre ─────────────────────────────────────────────────────
  {
    id: "hb-66",
    text: "Schiedsrichter, war das nicht ein Stürmerfoul?",
    translation: "Monsieur l'arbitre, ce n'était pas un passage en force ?",
    tip: "« Schiedsrichter » : « ch » au début, /ç/ doux dans « richter » ; « Stürmerfoul » : « cht » + « u » français.",
  },
  {
    id: "hb-67",
    text: "Entschuldigung, dürfen wir kurz wechseln, bevor es weitergeht?",
    translation: "Excusez-moi, on peut faire un changement rapide avant de reprendre ?",
    tip: "« dürfen » : « u » français ; « wechseln » : « chs » = « x », W = V.",
  },
  {
    id: "hb-68",
    text: "Ich habe den Ball zuerst berührt, das war Einwurf für uns.",
    translation: "J'ai touché le ballon en premier, c'est remise en jeu pour nous.",
    tip: "« zuerst » : /ts/ au début ; « berührt » : « u » français long + R allemand ensemble.",
  },
  {
    id: "hb-69",
    text: "War das Zeitspiel? Wir haben doch angegriffen.",
    translation: "C'était du jeu passif ? Pourtant on attaquait.",
    tip: "« Zeitspiel » : /ts/, « aï », puis « chp » ; « angegriffen » : double F net.",
  },
  {
    id: "hb-70",
    text: "Danke, Schiedsrichter, das war eine faire Entscheidung.",
    translation: "Merci, monsieur l'arbitre, c'était une décision juste.",
    tip: "« Entscheidung » : « ch » au milieu, « ei » = « aï », finale /ng/.",
  },
  {
    id: "hb-71",
    text: "Wie lange läuft die Zeitstrafe gegen unsere Nummer vier?",
    translation: "Combien de temps dure la pénalité contre notre numéro quatre ?",
    tip: "« läuft » : « oy » ; « Zeitstrafe » : /ts/ puis « cht » au milieu.",
  },
  {
    id: "hb-72",
    text: "Entschuldigung, das Foul war nicht absichtlich, es tut mir leid.",
    translation: "Excusez-moi, la faute n'était pas volontaire, je suis désolé.",
    tip: "« absichtlich » : deux /ç/ doux ; « leid » : « aï », « d » final = /t/.",
  },
  {
    id: "hb-73",
    text: "Dürfte ich fragen, warum der Treffer nicht zählt?",
    translation: "Puis-je demander pourquoi le but ne compte pas ?",
    tip: "« Dürfte » : « u » français ; « zählt » : /ts/ au début, « ä » long.",
  },
  {
    id: "hb-74",
    text: "Der Ball war hinter der Linie, das war ein Tor.",
    translation: "Le ballon avait franchi la ligne, c'était un but.",
    tip: "« hinter » finit /ɐ/ ; « Linie » = trois syllabes /li-ni-e/ ; « o » long dans « Tor ».",
  },
  {
    id: "hb-75",
    text: "Verstanden, wir stellen die Abwehr weiter zurück.",
    translation: "Compris, on recule encore la défense.",
    tip: "« Verstanden » : R allemand après « Ve » ; « zurück » : /ts/, deux « u » français.",
  },
  // ── Avant, pendant et après le match ───────────────────────────────────────
  {
    id: "hb-76",
    text: "Lasst uns gemeinsam warm machen, das Spiel beginnt gleich.",
    translation: "Échauffons-nous ensemble, le match commence bientôt.",
    tip: "« gemeinsam » : « ei » = « aï » ; « gleich » finit par le /ç/ doux.",
  },
  {
    id: "hb-77",
    text: "Heute gewinnen wir, wenn jeder für den anderen kämpft.",
    translation: "Aujourd'hui on gagne si chacun se bat pour les autres.",
    tip: "« gewinnen » : W = V ; « jeder » commence comme un « y » ; « kämpft » : /mpft/.",
  },
  {
    id: "hb-78",
    text: "Ich bin nervös, aber Nervosität bedeutet, dass es mir wichtig ist.",
    translation: "Je suis nerveux, mais la nervosité veut dire que c'est important pour moi.",
    tip: "« nervös » : R allemand, « eu » long ; « wichtig » : deux /ç/ doux.",
  },
  {
    id: "hb-79",
    text: "Gib mir ein Zeichen, wenn du den Kempa-Trick spielen willst.",
    translation: "Fais-moi un signe si tu veux jouer le kung-fu (Kempa).",
    tip: "« Zeichen » : /ts/, « aï », /ç/ doux ; L léger dans « willst ».",
  },
  {
    id: "hb-80",
    text: "Die erste Halbzeit war schwach, jetzt zeigen wir unser wahres Gesicht.",
    translation: "La première mi-temps était faible, maintenant on montre notre vrai visage.",
    tip: "« Halbzeit » : /ts/ au milieu ; « Gesicht » finit /ç/ doux + « t ».",
  },
  {
    id: "hb-81",
    text: "Trinkt alle etwas in der Pause, die zweite Hälfte wird hart.",
    translation: "Buvez tous quelque chose à la pause, la deuxième mi-temps sera dure.",
    tip: "« Hälfte » : « ä » court ; « zweite » : /tsv/ puis « aï ».",
  },
  {
    id: "hb-82",
    text: "Unser Rückraum muss mehr Druck auf die Abwehr machen.",
    translation: "Nos arrières doivent mettre plus de pression sur la défense.",
    tip: "« Druck » : R allemand après D, « u » court ; « Rückraum » : « u » français puis « ao ».",
  },
  {
    id: "hb-83",
    text: "Bleibt geduldig, die Lücke in der Abwehr kommt bestimmt.",
    translation: "Restez patients, la brèche dans la défense va venir.",
    tip: "« geduldig » finit /ç/ doux ; « Lücke » : « u » français court, L léger.",
  },
  {
    id: "hb-84",
    text: "Nach dem Abpfiff geben wir jedem Gegner die Hand.",
    translation: "Après le coup de sifflet final, on serre la main de chaque adversaire.",
    tip: "« Abpfiff » : le son /pf/ deux fois — un « p » qui glisse dans un « f ».",
  },
  {
    id: "hb-85",
    text: "Wir haben verdient gewonnen, aber bleiben bescheiden.",
    translation: "On a gagné en le méritant, mais on reste modestes.",
    tip: "« verdient » : R allemand, « ie » long ; « bescheiden » : « ch », « aï ».",
  },
  {
    id: "hb-86",
    text: "Die Niederlage tut weh, aber wir lernen daraus.",
    translation: "La défaite fait mal, mais on en tire des leçons.",
    tip: "« Niederlage » : « ie » long ; « daraus » : accent sur « raus ».",
  },
  {
    id: "hb-87",
    text: "Mein Ziel ist es, diese Saison fünfzig Tore zu werfen.",
    translation: "Mon objectif est de marquer cinquante buts cette saison.",
    tip: "« Ziel » : /ts/ + « i » long ; « fünfzig » : « u » français, finit /ç/ doux.",
  },
  {
    id: "hb-88",
    text: "Das Auswärtsspiel am Samstag wird unser schwerstes Spiel.",
    translation: "Le match à l'extérieur samedi sera notre match le plus dur.",
    tip: "« Auswärtsspiel » : « ao », puis « è », puis « chp » — découpe le mot composé.",
  },
  {
    id: "hb-89",
    text: "Ich wärme mich immer gründlich auf, um Verletzungen zu vermeiden.",
    translation: "Je m'échauffe toujours à fond pour éviter les blessures.",
    tip: "« gründlich » : « u » français, finit /ç/ doux ; « Verletzungen » : /ts/ + /ng/.",
  },
  {
    id: "hb-90",
    text: "Unsere Fans haben uns heute richtig nach vorne getragen.",
    translation: "Nos supporters nous ont vraiment portés aujourd'hui.",
    tip: "« richtig » : deux /ç/ doux ; « getragen » : R allemand après le T.",
  },
  {
    id: "hb-91",
    text: "Der Zeitnehmer zeigt an, dass noch dreißig Sekunden bleiben.",
    translation: "Le chronométreur indique qu'il reste trente secondes.",
    tip: "« Zeitnehmer » : /ts/ + « aï » ; « dreißig » : R allemand, « aï », finit /ç/ doux.",
  },
  {
    id: "hb-92",
    text: "Ich spiele lieber Rückraum links, weil ich rechts werfe.",
    translation: "Je préfère jouer arrière gauche parce que je tire de la main droite.",
    tip: "« lieber » : « ie » long, finit /ɐ/ ; « rechts » : /ç/ doux + « s ».",
  },
  {
    id: "hb-93",
    text: "Beim Anwurf stehen wir alle in der eigenen Hälfte.",
    translation: "À l'engagement, on est tous dans notre moitié de terrain.",
    tip: "« Anwurf » : W = V ; « eigenen » commence par « aï » ; « ä » court dans « Hälfte ».",
  },
  {
    id: "hb-94",
    text: "Passt auf die schnelle Mitte auf, direkt nach unserem Tor!",
    translation: "Attention à l'engagement rapide, juste après notre but !",
    tip: "« Passt » : double S net ; « direkt » : « t » final net ; deux R allemands.",
  },
  {
    id: "hb-95",
    text: "Unser Trainer sagt, Abwehr gewinnt Meisterschaften.",
    translation: "Notre coach dit que c'est la défense qui gagne les championnats.",
    tip: "« Meisterschaften » : « aï », puis « ch », finit « -ten » ; W = V dans « gewinnt ».",
  },
  {
    id: "hb-96",
    text: "Ich trainiere dreimal pro Woche plus ein Spiel am Wochenende.",
    translation: "Je m'entraîne trois fois par semaine plus un match le week-end.",
    tip: "« trainiere » : deux R allemands ; « Woche » : W = V, /x/ dur.",
  },
  {
    id: "hb-97",
    text: "Nach zwei Schritten muss ich prellen oder abspielen.",
    translation: "Après deux pas (trois appuis), je dois dribbler ou passer.",
    tip: "« Schritten » : « chr » — « ch » qui glisse dans le R allemand ; « prellen » : double L léger.",
  },
  {
    id: "hb-98",
    text: "Der Kempa-Trick klappt nur, wenn das Timing perfekt ist.",
    translation: "Le kung-fu ne marche que si le timing est parfait.",
    tip: "« klappt » : double P + T nets ; « perfekt » : R allemand, « t » final propre.",
  },
  {
    id: "hb-99",
    text: "Ich möchte später einmal in der Bundesliga spielen.",
    translation: "Je voudrais jouer un jour en Bundesliga.",
    tip: "« möchte » : « eu » + /ç/ doux ; « Bundesliga » : accent sur « Bun », L léger.",
  },
  {
    id: "hb-100",
    text: "Egal wie das Spiel ausgeht, wir geben niemals auf.",
    translation: "Peu importe comment finit le match, on n'abandonne jamais.",
    tip: "« Egal » : « a » long, L léger ; « niemals » : « ie » long ; « ausgeht » : « ao ».",
  },
  // ── Spécial gardien de but ─────────────────────────────────────────────────
  {
    id: "hb-101",
    text: "Ich habe den Ball, lauft schon in den Gegenstoß!",
    translation: "J'ai le ballon, partez déjà en contre-attaque !",
    tip: "« habe » : « h » soufflé (ne l'oublie pas) ; « lauft » : « ao » ; « Gegenstoß » : « ß » net.",
  },
  {
    id: "hb-102",
    text: "Abwehr, macht mir die Ecke zu, ich nehme die Mitte!",
    translation: "La défense, fermez-moi l'angle court, je prends le centre !",
    tip: "« Ecke » : « è » court, double consonne nette ; « nehme » : « e » long.",
  },
  {
    id: "hb-103",
    text: "Trainer, können wir noch ein paar Würfe auf mein Tor üben?",
    translation: "Coach, on peut encore travailler quelques tirs sur mon but ?",
    tip: "« Würfe » : « u » français court + R allemand ; « üben » : « u » français long.",
  },
  {
    id: "hb-104",
    text: "Beim Siebenmeter bleibe ich lange stehen und reagiere spät.",
    translation: "Sur le sept mètres, je reste debout longtemps et je réagis tard.",
    tip: "« bleibe » : « aï » ; « reagiere » : quatre syllabes /ré-a-gi-re/, R allemand.",
  },
  {
    id: "hb-105",
    text: "Ich sehe den Kreisläufer nicht, wer blockt ihn für mich?",
    translation: "Je ne vois pas le pivot, qui le bloque pour moi ?",
    tip: "« sehe » : « e » long, « h » muet ici ; « nicht » : /ç/ doux ; « blockt » : « t » net.",
  },
  {
    id: "hb-106",
    text: "Guter Block, so kann ich die lange Ecke halten.",
    translation: "Bon bloc, comme ça je peux couvrir l'angle long.",
    tip: "« Guter » finit /ɐ/ relâché ; « Ecke » : « è » + « ke » net ; « halten » : L léger.",
  },
  {
    id: "hb-107",
    text: "Ich werfe schnell ab, der Rechtsaußen ist schon losgelaufen.",
    translation: "Je relance vite, l'ailier droit est déjà parti.",
    tip: "« werfe » : W = V + R allemand ; « losgelaufen » : « o » long puis « ao ».",
  },
  {
    id: "hb-108",
    text: "Nach dem Gegentor bleibe ich ruhig und konzentriere mich neu.",
    translation: "Après un but encaissé, je reste calme et je me reconcentre.",
    tip: "« Gegentor » : deux « e »/« o » longs ; « konzentriere » : /ts/ au milieu.",
  },
  {
    id: "hb-109",
    text: "Der Wurf kam durch die Beine, das passiert mir nicht noch einmal.",
    translation: "Le tir est passé entre les jambes, ça ne m'arrivera plus.",
    tip: "« durch » : R allemand + /x/ léger ; « Beine » : « aï » ; « nicht » : /ç/ doux.",
  },
  {
    id: "hb-110",
    text: "Ich dirigiere die Abwehr, hört auf meine Kommandos!",
    translation: "Je dirige la défense, écoutez mes consignes !",
    tip: "« dirigiere » : R allemand doux, accent sur « gie » ; « hört » : « eu » long + R.",
  },
  {
    id: "hb-111",
    text: "Kurze Ecke ist zu, zwing ihn auf die lange Seite!",
    translation: "L'angle court est fermé, force-le à tirer côté long !",
    tip: "« Kurze » : /ts/ après le R ; « zwing » : /tsv/ au début, finale /ng/.",
  },
  {
    id: "hb-112",
    text: "Ich halte heute jeden Ball, werft ruhig aufs Tor!",
    translation: "Aujourd'hui j'arrête tous les ballons, tirez sans hésiter !",
    tip: "« halte » : L léger ; « jeden » commence comme « y » ; « werft » : W = V.",
  },
  {
    id: "hb-113",
    text: "Trainer, wie stelle ich mich beim Flügelwurf richtig?",
    translation: "Coach, comment je me place correctement sur un tir de l'aile ?",
    tip: "« stelle » : « cht » au début, L léger ; « Flügelwurf » : « u » français long, W = V.",
  },
  {
    id: "hb-114",
    text: "Meine Handschuhe sind rutschig, ich brauche kurz Harz.",
    translation: "Mes mains glissent, j'ai besoin d'un peu de résine.",
    tip: "« Handschuhe » : « ch » au milieu ; « rutschig » : « tch » puis /ç/ doux final.",
  },
  {
    id: "hb-115",
    text: "Gut gedeckt, durch euch sehe ich jeden Wurf früh genug.",
    translation: "Bien défendu, grâce à vous je vois chaque tir assez tôt.",
    tip: "« gedeckt » : « t » final net ; « früh » : « u » français long ; « genug » finit /k/.",
  },
  {
    id: "hb-116",
    text: "Beim Tempogegenstoß passe ich direkt auf die Mitte.",
    translation: "Sur la contre-attaque rapide, je passe directement au centre.",
    tip: "Découpe « Tempo-gegen-stoß » ; « passe » : double S net ; « direkt » : « t » net.",
  },
  {
    id: "hb-117",
    text: "Ich wärme meine Schultern extra gut auf, bevor ich ins Tor gehe.",
    translation: "J'échauffe particulièrement bien mes épaules avant d'aller dans le but.",
    tip: "« wärme » : W = V, « è » long ; « Schultern » : « ch » + L léger + finale /ɐn/.",
  },
  {
    id: "hb-118",
    text: "Der Ball ist im Aus, Abwurf für uns, alle nach vorne!",
    translation: "Le ballon est sorti, renvoi pour nous, tout le monde vers l'avant !",
    tip: "« Aus » : « ao » ; « Abwurf » : W = V ; « vorne » : R allemand + finale légère.",
  },
  {
    id: "hb-119",
    text: "Ein gehaltener Siebenmeter ist wie ein geworfenes Tor.",
    translation: "Un sept mètres arrêté, c'est comme un but marqué.",
    tip: "« gehaltener » : « h » soufflé, finit /ɐ/ ; « geworfenes » : W = V + R allemand.",
  },
  {
    id: "hb-120",
    text: "Als Torwart bin ich der erste Angreifer und der letzte Verteidiger.",
    translation: "Comme gardien, je suis le premier attaquant et le dernier défenseur.",
    tip: "« Torwart » : deux fois W = V et R allemand ; « Verteidiger » : « aï », finit /ɐ/.",
  },
];

export const HANDBALL_SCENARIOS: ScenarioItem[] = [
  {
    id: "hbs-1",
    context: "Du hast das Training verpasst und sprichst mit dem Trainer. (Tu as manqué l'entraînement et tu parles au coach.)",
    prompt: "Erkläre dem Trainer, warum du beim letzten Training gefehlt hast.",
    weakPhrase: "Ähm, ja, ich war halt nicht da, sorry.",
    strongPhrase:
      "Entschuldigung, dass ich am Dienstag gefehlt habe. Ich war krank, aber jetzt bin ich wieder fit und motiviert.",
  },
  {
    id: "hbs-2",
    context: "Du möchtest auf einer anderen Position spielen. (Tu veux jouer à un autre poste.)",
    prompt: "Frage den Trainer, ob du eine neue Position ausprobieren darfst.",
    weakPhrase: "Kann ich vielleicht mal woanders spielen oder so?",
    strongPhrase:
      "Trainer, ich würde gerne einmal im Rückraum spielen. Was muss ich dafür noch verbessern?",
  },
  {
    id: "hbs-3",
    context: "Der Trainer hat deine Abwehrarbeit kritisiert. (Le coach a critiqué ton travail défensif.)",
    prompt: "Reagiere auf die Kritik des Trainers.",
    weakPhrase: "Ja okay, mach ich halt irgendwie besser.",
    strongPhrase:
      "Danke für das Feedback. Ich verstehe, dass ich schneller zurücklaufen muss, und arbeite daran.",
  },
  {
    id: "hbs-4",
    context: "Du hast dich beim Training leicht verletzt. (Tu t'es blessé légèrement à l'entraînement.)",
    prompt: "Sage dem Trainer, dass du Schmerzen hast.",
    weakPhrase: "Es tut irgendwie ein bisschen weh, aber egal.",
    strongPhrase:
      "Trainer, meine Schulter tut seit dem Wurftraining weh. Ich möchte lieber pausieren, bevor es schlimmer wird.",
  },
  {
    id: "hbs-5",
    context: "Vor einem wichtigen Spiel fragt der Trainer nach deiner Einschätzung. (Avant un match important, le coach demande ton avis.)",
    prompt: "Sage dem Trainer, was du über den Gegner denkst.",
    weakPhrase: "Die sind halt gut, keine Ahnung, wird schwer.",
    strongPhrase:
      "Ihr Rückraum wirft sehr stark, aber ihre Abwehr ist langsam. Mit schnellen Gegenstößen haben wir eine gute Chance.",
  },
  {
    id: "hbs-6",
    context: "Du willst mehr Verantwortung im Team übernehmen. (Tu veux prendre plus de responsabilités dans l'équipe.)",
    prompt: "Frage den Trainer, wie du dem Team mehr helfen kannst.",
    weakPhrase: "Kann ich vielleicht mal mehr machen oder so?",
    strongPhrase:
      "Trainer, ich möchte mehr Verantwortung übernehmen. Woran soll ich arbeiten, um der Mannschaft noch mehr zu helfen?",
  },
  {
    id: "hbs-7",
    context: "Der Schiedsrichter hat gegen dich ein Foul gepfiffen, das du anders gesehen hast. (L'arbitre a sifflé une faute contre toi que tu as vue autrement.)",
    prompt: "Sprich respektvoll mit dem Schiedsrichter über die Entscheidung.",
    weakPhrase: "Das war nie im Leben ein Foul, echt jetzt!",
    strongPhrase:
      "Entschuldigung, Schiedsrichter, darf ich kurz fragen? Ich habe zuerst den Ball gespielt. Ich akzeptiere aber Ihre Entscheidung.",
  },
  {
    id: "hbs-8",
    context: "Ein Mitspieler hat einen wichtigen Wurf verworfen und ist frustriert. (Un coéquipier a raté un tir important et il est frustré.)",
    prompt: "Baue deinen Mitspieler wieder auf.",
    weakPhrase: "Ja, das war halt echt schlecht geworfen.",
    strongPhrase:
      "Kopf hoch, das passiert jedem. Deine Würfe haben uns hierher gebracht — den nächsten machst du rein.",
  },
  {
    id: "hbs-9",
    context: "Nach dem Spiel gibst du dem gegnerischen Kapitän die Hand. (Après le match, tu serres la main du capitaine adverse.)",
    prompt: "Gratuliere dem Gegner fair zum Sieg.",
    weakPhrase: "Ihr hattet halt Glück heute, egal.",
    strongPhrase:
      "Glückwunsch zum Sieg, ihr habt stark gespielt. Wir freuen uns auf das Rückspiel.",
  },
  {
    id: "hbs-10",
    context: "Der Trainer stellt dich vor die Wahl zwischen zwei Positionen für das Turnier. (Le coach te laisse choisir entre deux postes pour le tournoi.)",
    prompt: "Sage dem Trainer klar, welche Position du bevorzugst und warum.",
    weakPhrase: "Mir egal, mach du einfach, keine Ahnung.",
    strongPhrase:
      "Ich spiele lieber Linksaußen, weil ich im Tempogegenstoß meine Schnelligkeit einsetzen kann. Dort helfe ich dem Team am meisten.",
  },
];
